# Jekyll home: https://jekyllrb.com

# Themes: https://github.com/pages-themes/
# theme: jekyll-theme-architect
theme: jekyll-theme-dinky

markdown: kramdown

title: Logic Pro Scripter Guide
description: Andrew Hunt
